import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { World, seedNumber } from './world.js';
import { BLOCKS, BLOCK_BY_ID, HOTBAR_BLOCKS } from './blocks.js';

const $=id=>document.getElementById(id), EYE=1.62, H=1.8, R=.3, MAX=20;
let scene,camera,renderer,clock,world=null,player=null,state='MENU',locked=false,keys=Object.create(null),yaw=0,pitch=0,velocity=new THREE.Vector3(),onGround=false,health=20,hunger=20,hotIndex=0,hot=[],inventory={},target=null,breaking=null,outline=null,currentWorldKey=null,survival=0,lastSave=0,hungerClock=0,regenClock=0,hint=8;
let settings=loadSettings();
const APPLE={id:'apple',color:0xd65b55,food:5};
function loadSettings(){try{return{fov:75,sens:8,volume:.8,rd:3,coords:true,bob:true,...JSON.parse(localStorage.getItem('voxelSettings')||'{}')}}catch{return{fov:75,sens:8,volume:.8,rd:3,coords:true,bob:true}}}
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));if(id)$(id)?.classList.remove('hidden')}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x87c8ed);scene.fog=new THREE.Fog(0x87c8ed,55,150);camera=new THREE.PerspectiveCamera(settings.fov,innerWidth/innerHeight,.05,220);camera.up.set(0,1,0);camera.rotation.order='YXZ';renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;$('game').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xdff4ff,0x514638,1.8));const sun=new THREE.DirectionalLight(0xffffff,1.15);sun.position.set(60,100,35);scene.add(sun);clock=new THREE.Clock();events();syncSettings();buildHotbar();updateHud();requestAnimationFrame(loop)}
function events(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(state==='PLAYING'){if(e.code==='KeyE')openInventory();else if(e.code==='Escape')pause();else if(e.code==='KeyF')eat();else if(e.code.startsWith('Digit')){const n=+e.code.slice(5);if(n>0&&n<10){hotIndex=n-1;buildHotbar()}}}else if(state==='PAUSED'&&e.code==='Escape')resume();else if(state==='INVENTORY'&&e.code==='Escape')closeInventory()});document.addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('click',()=>{if(state==='PLAYING'&&!locked)lock()});document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;if(!locked&&state==='PLAYING')pause()});document.addEventListener('mousemove',e=>{if(!locked||state!=='PLAYING')return;const s=Number(settings.sens)*.0015;yaw-=e.movementX*s;pitch-=e.movementY*s;pitch=THREE.MathUtils.clamp(pitch,-Math.PI/2+.02,Math.PI/2-.02)});renderer.domElement.addEventListener('mousedown',e=>{if(!locked||state!=='PLAYING')return;e.preventDefault();if(e.button===0)startBreak();if(e.button===2)place()});renderer.domElement.addEventListener('mouseup',e=>{if(e.button===0)breaking=null});renderer.domElement.addEventListener('wheel',e=>{if(!locked||state!=='PLAYING')return;e.preventDefault();hotIndex=(hotIndex+(e.deltaY>0?1:-1)+9)%9;buildHotbar()},{passive:false});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());$('playBtn').onclick=()=>{refreshWorlds();screen('worlds');state='WORLDS'};$('worldsBtn').onclick=()=>{refreshWorlds();screen('worlds');state='WORLDS'};$('createBtn').onclick=()=>{screen('create');state='CREATE'};$('startWorld').onclick=startNew;$('resumeBtn').onclick=resume;$('quitBtn').onclick=()=>{save();leaveMenu()};$('settingsBtn').onclick=()=>openSettings('menu');$('pauseSettings').onclick=()=>openSettings('pause');$('aboutBtn').onclick=()=>{screen('about');state='ABOUT'};$('closeInv').onclick=closeInventory;$('closeInvBottom').onclick=closeInventory;$('respawnBtn').onclick=respawn;$('deadMenu').onclick=leaveMenu;document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{screen(b.dataset.back);state=b.dataset.back==='menu'?'MENU':b.dataset.back.toUpperCase();if(b.dataset.back==='worlds')refreshWorlds()});$('fov').oninput=()=>{camera.fov=+$('fov').value;camera.updateProjectionMatrix();saveSettings();syncSettings()};$('sens').oninput=()=>{saveSettings();syncSettings()};$('volume').oninput=()=>{saveSettings();syncSettings()};$('rd').oninput=()=>{saveSettings();syncSettings()};$('coordsToggle').onchange=saveSettings;$('bobToggle').onchange=saveSettings}
function lock(){try{const p=renderer.domElement.requestPointerLock();if(p&&typeof p.catch==='function')p.catch(()=>{})}catch{}}
function syncSettings(){$('fov').value=settings.fov;$('sens').value=settings.sens;$('volume').value=settings.volume;$('rd').value=settings.rd;$('coordsToggle').checked=settings.coords!==false;$('bobToggle').checked=settings.bob!==false;$('fovValue').textContent=settings.fov;$('sensValue').textContent=settings.sens;$('volumeValue').textContent=Math.round(settings.volume*100)+'%';$('rdValue').textContent=settings.rd}
function saveSettings(){settings={fov:+$('fov').value,sens:+$('sens').value,volume:+$('volume').value,rd:+$('rd').value,coords:$('coordsToggle').checked,bob:$('bobToggle').checked};localStorage.setItem('voxelSettings',JSON.stringify(settings))}
function resetInventory(){inventory={};for(const id of Object.keys(BLOCKS))inventory[id]=0;inventory.apple=8;hot=HOTBAR_BLOCKS.map((id,i)=>({id,count:i===1?16:0}))}
function startNew(){const name=$('worldName').value.trim()||'New World';world=new World(seedNumber($('worldSeed').value.trim()),$('worldType').value);world.findSpawn();player={pos:new THREE.Vector3(world.spawn.x,world.spawn.y,world.spawn.z)};health=hunger=20;survival=hungerClock=regenClock=0;resetInventory();currentWorldKey='voxelWorld:'+name;save();lock();enterWorld()}
function loadWorld(key){let d;try{d=JSON.parse(localStorage.getItem(key))}catch{return}if(!d)return;currentWorldKey=key;world=new World(d.seed,d.type);world.findSpawn();world.modified=new Map(Object.entries(d.modified||{}).map(([k,v])=>[k,+v]));player={pos:new THREE.Vector3(d.player?.x??.5,d.player?.y??world.spawn.y,d.player?.z??.5)};health=THREE.MathUtils.clamp(+(d.health??20),0,20);hunger=THREE.MathUtils.clamp(+(d.hunger??20),0,20);inventory={};for(const id of Object.keys(BLOCKS))inventory[id]=0;Object.assign(inventory,d.inventory||{});inventory.apple=+(d.inventory?.apple??d.apple??0);hot=Array.isArray(d.hot)?d.hot.slice(0,9):HOTBAR_BLOCKS.map(id=>({id,count:0}));while(hot.length<9)hot.push({id:HOTBAR_BLOCKS[hot.length]||'dirt',count:0});survival=0;lock();enterWorld()}
function enterWorld(){screen(null);$('loading').classList.remove('hidden');$('hud').classList.add('hidden');state='LOADING';world.clearMeshes();let n=0,total=8,dist=Math.max(1,+$('renderDistance').value||settings.rd||3);const step=()=>{n++;world.loadNear(player.pos.x,player.pos.z,Math.max(1,Math.ceil(dist*Math.sqrt(n/total))),scene);$('loadBar').style.width=n/total*100+'%';$('loadText').textContent=`Generating world... ${n}/${total}`;if(n<total)setTimeout(step,20);else{safeSpawn();$('loading').classList.add('hidden');$('hud').classList.remove('hidden');state='PLAYING';hint=8;updateHud()}};step()}
function safeSpawn(){let x=Math.floor(player.pos.x),z=Math.floor(player.pos.z),y=Math.floor(player.pos.y);while(y>1&&!solid(x,y-1,z))y--;if(solid(x,y-1,z)&&!solid(x,y,z)&&!solid(x,y+1,z))player.pos.y=y+.01}
function refreshWorlds(){const box=$('worldList');box.innerHTML='';const list=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('voxelWorld:'))try{list.push([k,JSON.parse(localStorage.getItem(k))])}catch{localStorage.removeItem(k)}}for(const [k,d] of list){const row=document.createElement('div');row.className='worldRow';const info=document.createElement('div');info.innerHTML=`<strong>${esc(d.name)}</strong><small>Seed: ${esc(d.seed)}</small>`;const play=document.createElement('button');play.textContent='PLAY';play.onclick=()=>loadWorld(k);const del=document.createElement('button');del.textContent='DELETE';del.className='delete';del.onclick=()=>{if(confirm(`Delete "${d.name}"?`)){localStorage.removeItem(k);refreshWorlds()}};row.append(info,play,del);box.append(row)}}
function save(){if(!world||!player||!currentWorldKey)return;localStorage.setItem(currentWorldKey,JSON.stringify({saveVersion:2,name:currentWorldKey.slice(12),seed:world.seed,type:world.type,player:{x:player.pos.x,y:player.pos.y,z:player.pos.z},health,hunger,inventory,hot,modified:Object.fromEntries(world.modified),time:survival}))}
function leaveMenu(){save();document.exitPointerLock();state='MENU';target=breaking=null;if(outline)outline.visible=false;$('hud').classList.add('hidden');screen('menu')}
function solid(x,y,z){const b=BLOCK_BY_ID[world.get(x,y,z)];return!!(b?.solid&&!b.transparent)}
function collide(pos){const minX=Math.floor(pos.x-R),maxX=Math.floor(pos.x+R),minY=Math.floor(pos.y),maxY=Math.floor(pos.y+H-.001),minZ=Math.floor(pos.z-R),maxZ=Math.floor(pos.z+R);for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)for(let z=minZ;z<=maxZ;z++)if(solid(x,y,z))return true;return false}
function moveAxis(a,amount){if(!amount)return false;const p=player.pos.clone();p[a]+=amount;if(!collide(p)){player.pos[a]=p[a];return false}return true}
function updatePlayer(dt){const f=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),move=new THREE.Vector3();if(keys.KeyW)move.add(f);if(keys.KeyS)move.sub(f);if(keys.KeyD)move.add(r);if(keys.KeyA)move.sub(r);if(move.lengthSq())move.normalize();const sprint=!!(keys.ShiftLeft||keys.ShiftRight)&&move.lengthSq()>0,speed=sprint?7:4.5;velocity.x=THREE.MathUtils.damp(velocity.x,move.x*speed,20,dt);velocity.z=THREE.MathUtils.damp(velocity.z,move.z*speed,20,dt);if(keys.Space&&onGround){velocity.y=8;onGround=false}velocity.y-=22*dt;const falling=velocity.y;moveAxis('x',velocity.x*dt);moveAxis('z',velocity.z*dt);const hit=moveAxis('y',velocity.y*dt);if(hit){if(velocity.y<0){onGround=true;if(falling<-11)damage(Math.min(10,Math.floor((Math.abs(falling)-10)*.7)))}velocity.y=0}else onGround=false;if(player.pos.y<-12){health=0;die();return}let bob=settings.bob!==false&&onGround&&move.lengthSq()?Math.sin(performance.now()*.012*(sprint?1.4:1))*.025:0;camera.position.set(player.pos.x,player.pos.y+EYE+bob,player.pos.z);camera.rotation.y=yaw;camera.rotation.x=pitch}
function survivalTick(dt){survival+=dt;hungerClock+=dt;regenClock+=dt;if(hungerClock>=30){hungerClock=0;hunger=Math.max(0,hunger-1)}if(hunger<=0&&Math.floor(survival)!==Math.floor(survival-dt))damage(1);if(hunger>=18&&health<20&&regenClock>=4){regenClock=0;health=Math.min(20,health+1)}}
function damage(n){if(state!=='PLAYING'||n<=0)return;health=Math.max(0,health-n);if(health<=0)die()}
function eat(){if(hunger>=20||inventory.apple<=0)return;inventory.apple--;hunger=Math.min(20,hunger+APPLE.food);buildHotbar()}
function raycast(){const origin=camera.position.clone(),dir=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion).normalize(),p=origin.clone(),step=.035;let prev=null;for(let d=0;d<=7;d+=step){const c={x:Math.floor(p.x),y:Math.floor(p.y),z:Math.floor(p.z)};if(!prev||c.x!==prev.x||c.y!==prev.y||c.z!==prev.z){const id=world.get(c.x,c.y,c.z);if(id&&BLOCK_BY_ID[id]?.solid){const normal=prev?new THREE.Vector3(prev.x-c.x,prev.y-c.y,prev.z-c.z):dir.clone().multiplyScalar(-1).set(Math.sign(dir.x)?-Math.sign(dir.x):0,Math.sign(dir.y)?-Math.sign(dir.y):0,Math.sign(dir.z)?-Math.sign(dir.z):0);return{...c,id,normal,distance:d}}prev=c}p.addScaledVector(dir,step)}return null}
function updateOutline(){if(!outline){outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.006,1.006,1.006)),new THREE.LineBasicMaterial({color:0xf3f7dc,transparent:true,opacity:.72}));scene.add(outline)}if(!target){outline.visible=false;return}outline.visible=true;outline.position.set(target.x+.5,target.y+.5,target.z+.5);$('targetLabel').textContent=BLOCK_BY_ID[target.id]?.name||target.id}
function startBreak(){if(!target)return;const b=BLOCK_BY_ID[target.id];breaking={...target,time:0,need:Math.max(.12,(b?.hardness||1)/2)} }
function breakTick(dt){if(!breaking)return;if(!locked||!target||target.x!==breaking.x||target.y!==breaking.y||target.z!==breaking.z||target.id!==breaking.id){breaking=null;progress(0);return}breaking.time+=dt;const p=Math.min(1,breaking.time/breaking.need);progress(p);if(p>=1){const b=BLOCK_BY_ID[breaking.id];world.set(breaking.x,breaking.y,breaking.z,0);if(b?.drop)give(b.drop,1);else if(breaking.id!==22)give(breaking.id,1);breaking=null;progress(0)}}
function progress(p){const b=$('breakBar');if(!p){b.classList.add('hidden');b.querySelector('i').style.width='0';return}b.classList.remove('hidden');b.querySelector('i').style.width=p*100+'%'}
function place(){const s=hot[hotIndex];if(!s?.count||!BLOCK_BY_ID[s.id]||!target)return;const n=target.normal,x=target.x+n.x,y=target.y+n.y,z=target.z+n.z;if(!Number.isInteger(x)||!Number.isInteger(y)||!Number.isInteger(z)||world.get(x,y,z)!==0)return;const p=new THREE.Vector3(x+.5,y,z+.5);if(collide(p))return;world.set(x,y,z,BLOCK_BY_ID[s.id].id);s.count--;buildHotbar()}
function give(id,n){if(!id)return;let s=hot.find(x=>x.id===id&&x.count<64);if(s)s.count=Math.min(64,s.count+n);else{s=hot.find(x=>!x.id||x.count<=0);if(s&&BLOCK_BY_ID[id]){s.id=id;s.count=n}else inventory[id]=(inventory[id]||0)+n}buildHotbar()}
function symbol(id){return id==='apple'?'●':BLOCK_BY_ID[id]?'■':'·'}function color(id){return id==='apple'?APPLE.color:BLOCK_BY_ID[id]?.color||0xffffff}
function buildHotbar(){const box=$('hotbar');box.innerHTML='';hot.forEach((s,i)=>{const d=document.createElement('div');d.className='hot '+(i===hotIndex?'sel':'');d.innerHTML=`<span class="num">${i+1}</span><span class="item-icon" style="color:#${color(s.id).toString(16).padStart(6,'0')}">${symbol(s.id)}</span><small>${s.count>0?s.count:''}</small>`;d.onclick=()=>{hotIndex=i;buildHotbar()};box.appendChild(d)})}
function renderInventory(){const g=$('invGrid');g.innerHTML='';for(const [id,count] of Object.entries(inventory))if(count>0){const d=document.createElement('div');d.className='slot';d.innerHTML=`<b style="color:#${color(id).toString(16).padStart(6,'0')}">${symbol(id)}</b><span>${id.replaceAll('_',' ')}</span><em>${count}</em>`;g.appendChild(d)}const h=$('invHotbar');h.innerHTML='';hot.forEach((s,i)=>{const d=document.createElement('div');d.className='slot '+(i===hotIndex?'selected':'');d.innerHTML=`<b>${symbol(s.id)}</b><em>${s.count||''}</em>`;h.appendChild(d)})}
function openInventory(){state='INVENTORY';document.exitPointerLock();renderInventory();$('inventory').classList.remove('hidden')}function closeInventory(){$('inventory').classList.add('hidden');state='PLAYING';lock()}function pause(){if(state!=='PLAYING')return;state='PAUSED';document.exitPointerLock();screen('pause')}function resume(){if(state!=='PAUSED')return;screen(null);state='PLAYING';$('hud').classList.remove('hidden');lock()}function die(){if(state==='DEAD')return;health=0;document.exitPointerLock();state='DEAD';screen('dead');$('hud').classList.add('hidden');save()}function respawn(){health=hunger=20;player.pos.set(world.spawn.x,world.spawn.y,world.spawn.z);velocity.set(0,0,0);onGround=false;screen(null);$('hud').classList.remove('hidden');state='PLAYING';lock();updateHud()}
function updateHud(){const hi=$('healthIcons'),fi=$('hungerIcons');hi.innerHTML=fi.innerHTML='';for(let i=0;i<10;i++){const h=document.createElement('span');h.className='icon '+(health>=i*2+2?'full':health>i*2?'half':'empty')+' health';hi.appendChild(h);const f=document.createElement('span');f.className='icon '+(hunger>=i*2+2?'full':hunger>i*2?'half':'empty')+' food';fi.appendChild(f)}$('healthText').textContent=`${Math.ceil(health)} / 20`;$('hungerText').textContent=`${Math.ceil(hunger)} / 20`;$('coords').textContent=settings.coords===false||!player?'':`XYZ ${player.pos.x.toFixed(1)}  ${player.pos.y.toFixed(1)}  ${player.pos.z.toFixed(1)}`}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(state==='PLAYING'&&world&&player){updatePlayer(dt);survivalTick(dt);target=raycast();updateOutline();breakTick(dt);updateHud();if(hint>0){hint-=dt;$('hint').style.opacity=Math.max(0,hint/2)}else $('hint').style.opacity=0;if(survival-lastSave>=10){save();lastSave=survival}}renderer.render(scene,camera)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();