import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { World, seedNumber } from './world.js';
import { BLOCKS, BLOCK_BY_ID, HOTBAR_BLOCKS } from './blocks.js';
import { Multiplayer } from './multiplayer.js';
const $=id=>document.getElementById(id),EYE=1.62,HEIGHT=1.8,RADIUS=.3,MAX=20;
let scene,camera,renderer,clock,world=null,player=null,state='MENU',locked=false,keys=Object.create(null),yaw=0,pitch=0,velocity=new THREE.Vector3(),onGround=false,health=20,hunger=20,hotIndex=0,hot=[],inventory={},target=null,breaking=null,outline=null,currentWorldKey=null,hungerClock=0,regenClock=0,lastSave=0;
let settings=loadSettings(),mp=null,lastChunkX=null,lastChunkZ=null,mpStateClock=0,remotePlayers=new Map();
function loadSettings(){try{return{fov:75,sens:8,volume:.8,rd:3,coords:true,bob:true,...JSON.parse(localStorage.getItem('voxelSettings')||'{}')}}catch{return{fov:75,sens:8,volume:.8,rd:3,coords:true,bob:true}}}
function saveSettings(){settings={fov:+$('fov').value,sens:+$('sens').value,volume:+$('volume').value,rd:+$('rd').value,coords:$('coordsToggle').checked,bob:$('bobToggle').checked};localStorage.setItem('voxelSettings',JSON.stringify(settings));applySettings()}
function syncSettings(){$('fov').value=settings.fov;$('sens').value=settings.sens;$('volume').value=settings.volume;$('rd').value=settings.rd;$('coordsToggle').checked=settings.coords!==false;$('bobToggle').checked=settings.bob!==false;$('fovValue').textContent=settings.fov;$('sensValue').textContent=settings.sens;$('volumeValue').textContent=Math.round(settings.volume*100)+'%';$('rdValue').textContent=settings.rd}
function applySettings(){camera.fov=Number(settings.fov)||75;camera.updateProjectionMatrix();scene.fog.near=30+Number(settings.rd)*8;scene.fog.far=70+Number(settings.rd)*28;syncSettings()}
function screen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));if(id)$(id)?.classList.remove('hidden')}
function setState(next){state=next;const gameplay=next==='PLAYING'||next==='INVENTORY';$('hud').classList.toggle('hidden',!gameplay);if(next!=='PLAYING'){keys=Object.create(null);breaking=null}if(next!=='PLAYING'&&locked){document.exitPointerLock()}}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x86c8ee);scene.fog=new THREE.Fog(0x86c8ee,55,150);camera=new THREE.PerspectiveCamera(settings.fov,innerWidth/innerHeight,.05,240);camera.up.set(0,1,0);camera.rotation.order='YXZ';renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;$('game').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xe5f5ff,0x51483d,1.9));const sun=new THREE.DirectionalLight(0xffffff,1.2);sun.position.set(60,100,40);scene.add(sun);clock=new THREE.Clock();setupEvents();mp=new Multiplayer({onRemote:handleNetwork,onError:e=>setMpStatus('CONNECTION ERROR',e?.message||'Connection failed'),onStatus:(s,m)=>setMpStatus(s,m),onBlock:(b)=>applyNetworkBlock(b)});syncSettings();buildHotbar();updateHud();screen('menu');setState('MENU');requestAnimationFrame(loop)}
function setupEvents(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(state==='PLAYING'){if(e.code==='KeyE'){e.preventDefault();openInventory()}else if(e.code==='Escape'){e.preventDefault();pause()}else if(e.code==='KeyF'){e.preventDefault();eat()}else if(e.code.startsWith('Digit')){const n=Number(e.code.slice(5));if(n>=1&&n<=9){hotIndex=n-1;buildHotbar()}}}else if(state==='PAUSED'&&e.code==='Escape')resume();else if(state==='INVENTORY'&&e.code==='Escape')closeInventory()});document.addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('click',()=>{if(state==='PLAYING'&&!locked)requestLock()});document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;if(!locked&&state==='PLAYING')pause()});document.addEventListener('mousemove',e=>{if(!locked||state!=='PLAYING')return;const s=(Number(settings.sens)||8)*.0016;yaw-=e.movementX*s;pitch-=e.movementY*s;pitch=THREE.MathUtils.clamp(pitch,-Math.PI/2+.01,Math.PI/2-.01)});renderer.domElement.addEventListener('mousedown',e=>{if(!locked||state!=='PLAYING')return;e.preventDefault();if(e.button===0)startBreak();else if(e.button===2)place()});renderer.domElement.addEventListener('mouseup',e=>{if(e.button===0)breaking=null});renderer.domElement.addEventListener('wheel',e=>{if(!locked||state!=='PLAYING')return;e.preventDefault();hotIndex=(hotIndex+(e.deltaY>0?1:-1)+9)%9;buildHotbar()},{passive:false});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());$('playBtn').onclick=playFlow;$('multiplayerBtn').onclick=()=>{screen('multiplayer');setState('MULTIPLAYER')};$('createRoomBtn').onclick=createMultiplayerRoom;$('joinRoomBtn').onclick=joinMultiplayerRoom;$('worldsBtn').onclick=worldsFlow;$('createBtn').onclick=()=>{screen('create');setState('CREATE')};$('startWorld').onclick=startNew;$('resumeBtn').onclick=resume;$('quitBtn').onclick=()=>{save();leaveMenu()};$('settingsBtn').onclick=()=>openSettings('menu');$('pauseSettings').onclick=()=>openSettings('pause');$('aboutBtn').onclick=()=>{screen('about');setState('ABOUT')};$('closeInv').onclick=closeInventory;$('closeInvBottom').onclick=closeInventory;$('respawnBtn').onclick=respawn;$('deadMenu').onclick=leaveMenu;document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>navigateBack(b.dataset.back));$('fov').oninput=()=>{settings.fov=+$('fov').value;applySettings();saveSettings()};$('sens').oninput=()=>{settings.sens=+$('sens').value;syncSettings();saveSettings()};$('volume').oninput=()=>{settings.volume=+$('volume').value;syncSettings();saveSettings()};$('rd').oninput=()=>{settings.rd=+$('rd').value;applySettings();saveSettings()};$('coordsToggle').onchange=saveSettings;$('bobToggle').onchange=saveSettings}
function requestLock(){try{const p=renderer.domElement.requestPointerLock();if(p?.catch)p.catch(()=>{})}catch{}}
function playFlow(){const worlds=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('voxelWorld:'))worlds.push(k)}if(worlds.length)loadWorld(worlds[0]);else{screen('create');setState('CREATE')}}
function worldsFlow(){refreshWorlds();screen('worlds');setState('WORLDS')}
function navigateBack(id){if(id==='menu'){screen('menu');setState('MENU')}else if(id==='worlds'){refreshWorlds();screen('worlds');setState('WORLDS')}else{screen(id);setState(id.toUpperCase())}}
function openSettings(from){$('settings').dataset.return=from;syncSettings();screen('settings');setState('SETTINGS')}
function resetInventory(){inventory={};for(const id of Object.keys(BLOCKS))inventory[id]=0;inventory.apple=8;hot=HOTBAR_BLOCKS.map((id,i)=>({id,count:i===1?16:0}));hotIndex=0}
function startNew(){const name=$('worldName').value.trim()||'New World';const key='voxelWorld:'+name;world=new World(seedNumber($('worldSeed').value.trim()),$('worldType').value);world.findSpawn();player={pos:new THREE.Vector3(world.spawn.x,world.spawn.y,world.spawn.z)};health=20;hunger=20;hungerClock=regenClock=0;resetInventory();currentWorldKey=key;save();enterWorld()}
function loadWorld(key){let d;try{d=JSON.parse(localStorage.getItem(key))}catch{return}if(!d)return;currentWorldKey=key;world=new World(d.seed,d.type);world.modified=new Map(Object.entries(d.modified||{}).map(([k,v])=>[k,Number(v)]));world.findSpawn();player={pos:new THREE.Vector3(d.player?.x??world.spawn.x,d.player?.y??world.spawn.y,d.player?.z??world.spawn.z)};health=THREE.MathUtils.clamp(Number(d.health??20),0,20);hunger=THREE.MathUtils.clamp(Number(d.hunger??20),0,20);inventory={};for(const id of Object.keys(BLOCKS))inventory[id]=0;Object.assign(inventory,d.inventory||{});inventory.apple=Number(d.inventory?.apple??8);hot=Array.isArray(d.hot)?d.hot.slice(0,9):HOTBAR_BLOCKS.map(id=>({id,count:0}));while(hot.length<9)hot.push({id:HOTBAR_BLOCKS[hot.length]||'dirt',count:0});hotIndex=Math.min(Number(d.hotIndex??0),8);enterWorld()}
function enterWorld(){screen(null);$('loading').classList.remove('hidden');setState('LOADING');world.clearMeshes();lastChunkX=lastChunkZ=null;let step=0,total=7;const dist=Math.max(1,Number(settings.rd)||3);const build=()=>{step++;world.loadNear(player.pos.x,player.pos.z,Math.max(1,Math.ceil(dist*Math.sqrt(step/total))),scene);$('loadBar').style.width=`${step/total*100}%`;$('loadText').textContent=`Generating world... ${step}/${total}`;if(step<total)setTimeout(build,15);else{safeSpawn();$('loading').classList.add('hidden');screen(null);setState('PLAYING');updateHud();requestLock()}};build()}
function safeSpawn(){const x=Math.floor(player.pos.x),z=Math.floor(player.pos.z);let y=world.height(x,z)+1.01;while(y<64&&solid(x,Math.floor(y),z))y+=1;player.pos.set(x+.5,y,z+.5);velocity.set(0,0,0);onGround=false}
function refreshWorlds(){const box=$('worldList');box.innerHTML='';for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith('voxelWorld:'))continue;let d;try{d=JSON.parse(localStorage.getItem(k))}catch{continue}const row=document.createElement('div');row.className='worldRow';const info=document.createElement('div');info.className='worldInfo';const title=document.createElement('strong');title.textContent=d.name||k.slice(12);const seed=document.createElement('small');seed.textContent=`Seed: ${d.seed}`;info.append(title,seed);const play=document.createElement('button');play.textContent='PLAY';play.onclick=()=>loadWorld(k);const del=document.createElement('button');del.textContent='DELETE';del.className='delete';del.onclick=()=>{localStorage.removeItem(k);refreshWorlds()};row.append(info,play,del);box.append(row)}}
function createMultiplayerRoom(){const name=$('mpName').value.trim()||'Player';ensureMultiplayerHostWorld();mp.create(name).then(()=>{syncMultiplayerWorld();enterWorld()}).catch(()=>{});}
function joinMultiplayerRoom(){const name=$('mpName').value.trim()||'Player',roomId=$('roomId').value.trim();if(!roomId){setMpStatus('CONNECTION ERROR','Enter a room ID');return}mp.join(roomId,name).then(()=>setMpStatus('CONNECTED','Waiting for host world...')).catch(()=>{});}
function ensureMultiplayerHostWorld(){if(world)return;const name='Multiplayer World';world=new World(Math.floor(Math.random()*2147483647),'Normal');world.findSpawn();player={pos:new THREE.Vector3(world.spawn.x,world.spawn.y,world.spawn.z)};health=20;hunger=20;resetInventory();currentWorldKey='voxelWorld:'+name;save();}
function syncMultiplayerWorld(){if(!mp?.peer||!world)return;mp.setWorldInfo({seed:world.seed,type:world.type,modified:Object.fromEntries(world.modified)});}
function setMpStatus(s,m=''){const el=$('mpStatus');if(el)el.textContent=m?`${s} — ${m}`:s;const room=$('mpRoom');if(room)room.textContent=mp?.room?`ROOM: ${mp.room}`:'';}
function handleNetwork(m){if(!m)return;if(m.type==='world-info'){if(mp.isHost)return;const w=m.world;if(!w||!Number.isFinite(Number(w.seed)))return;world=new World(Number(w.seed),String(w.type||'Normal'));world.modified=new Map(Object.entries(w.modified||{}).map(([k,v])=>[k,Number(v)]));world.findSpawn();player={pos:new THREE.Vector3(world.spawn.x,world.spawn.y,world.spawn.z)};health=20;hunger=20;resetInventory();currentWorldKey=null;enterWorld();return}if(m.type==='block'){applyNetworkBlock(m.block);return}if(m.type==='player-join'||m.type==='state'){const p=m.player;if(!p||p.networkId===mp.local?.networkId)return;let r=remotePlayers.get(p.networkId);if(!r)r=createRemote(p);r.target.position.set(p.position.x,p.position.y,p.position.z);r.target.rotation.set(p.rotation.x,p.rotation.y,0,'YXZ');r.name=p.displayName;return}if(m.type==='player-leave'){removeRemote(m.networkId)}}
function createRemote(p){const g=new THREE.Group(),mat=new THREE.MeshLambertMaterial({color:0x5e8fbd}),skin=new THREE.MeshLambertMaterial({color:0xc28e6b});const body=new THREE.Mesh(new THREE.BoxGeometry(.6,1.0,.32),mat);body.position.y=.9;const head=new THREE.Mesh(new THREE.BoxGeometry(.62,.62,.62),skin);head.position.y=1.7;g.add(body,head);g.position.set(p.position.x,p.position.y,p.position.z);scene.add(g);const r={target:g,current:new THREE.Vector3().copy(g.position),name:p.displayName};remotePlayers.set(p.networkId,r);return r}
function removeRemote(id){const r=remotePlayers.get(id);if(!r)return;r.target.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose()});r.target.parent?.remove(r.target);remotePlayers.delete(id)}
function applyNetworkBlock(b){if(!world||!b)return;world.set(b.x,b.y,b.z,b.id)}
function changeBlock(x,y,z,id){if(mp?.peer&&mp.hostId)mp.requestBlock({x,y,z,id});else world.set(x,y,z,id)}
function updateRemotePlayers(dt){for(const r of remotePlayers.values()){const a=.min?0:1;r.current.lerp(r.target.position,1-Math.exp(-12*dt));r.target.position.copy(r.current)}}
function save(){if(!world||!player||!currentWorldKey)return;localStorage.setItem(currentWorldKey,JSON.stringify({saveVersion:3,name:currentWorldKey.slice(12),seed:world.seed,type:world.type,player:{x:player.pos.x,y:player.pos.y,z:player.pos.z},health,hunger,inventory,hot,hotIndex,modified:Object.fromEntries(world.modified)}))}
function leaveMenu(){save();if(locked)document.exitPointerLock();world?.clearMeshes();target=breaking=null;screen('menu');setState('MENU')}
function solid(x,y,z){const b=BLOCK_BY_ID[world.get(x,y,z)];return!!(b?.solid&&!b.transparent)}
function collides(pos){const minX=Math.floor(pos.x-RADIUS),maxX=Math.floor(pos.x+RADIUS),minY=Math.floor(pos.y),maxY=Math.floor(pos.y+HEIGHT-.001),minZ=Math.floor(pos.z-RADIUS),maxZ=Math.floor(pos.z+RADIUS);for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)for(let z=minZ;z<=maxZ;z++)if(solid(x,y,z))return true;return false}
function moveAxis(axis,amount){if(!amount)return false;const next=player.pos.clone();next[axis]+=amount;if(!collides(next)){player.pos.copy(next);return false}return true}
function streamChunks(){if(!world||!player)return;const {cx,cz}=world.chunkCoords(player.pos.x,player.pos.z);if(cx!==lastChunkX||cz!==lastChunkZ){lastChunkX=cx;lastChunkZ=cz;world.loadNear(player.pos.x,player.pos.z,Math.max(1,Number(settings.rd)||3),scene)}}
function updatePlayer(dt){const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),move=new THREE.Vector3();if(keys.KeyW)move.add(forward);if(keys.KeyS)move.sub(forward);if(keys.KeyD)move.add(right);if(keys.KeyA)move.sub(right);if(move.lengthSq())move.normalize();const sprint=(keys.ShiftLeft||keys.ShiftRight)&&move.lengthSq()>0,speed=sprint?7:4.5;velocity.x=THREE.MathUtils.damp(velocity.x,move.x*speed,18,dt);velocity.z=THREE.MathUtils.damp(velocity.z,move.z*speed,18,dt);if(keys.Space&&onGround){velocity.y=8;onGround=false}velocity.y-=22*dt;const falling=velocity.y;moveAxis('x',velocity.x*dt);moveAxis('z',velocity.z*dt);const hit=moveAxis('y',velocity.y*dt);if(hit){if(velocity.y<0){onGround=true;if(falling<-11)damage(Math.min(10,Math.floor((Math.abs(falling)-10)*.7)))}velocity.y=0}else onGround=false;if(player.pos.y<-12){health=0;die();return}const bob=settings.bob!==false&&onGround&&move.lengthSq()?Math.sin(performance.now()*.012*(sprint?1.4:1))*.025:0;camera.position.set(player.pos.x,player.pos.y+EYE+bob,player.pos.z);camera.rotation.set(pitch,yaw,0,'YXZ')}
function raycast(){const origin=camera.position.clone(),dir=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion).normalize();let previous=null;for(let d=0;d<=8;d+=.025){const p=origin.clone().addScaledVector(dir,d),c={x:Math.floor(p.x),y:Math.floor(p.y),z:Math.floor(p.z)};if(!previous||c.x!==previous.x||c.y!==previous.y||c.z!==previous.z){const id=world.get(c.x,c.y,c.z);if(id&&BLOCK_BY_ID[id]?.solid)return{...c,id,normal:new THREE.Vector3(previous.x-c.x,previous.y-c.y,previous.z-c.z),distance:d};previous=c}}return null}
function updateOutline(){if(!outline){outline=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(1.01,1.01,1.01)),new THREE.LineBasicMaterial({color:0xf4f5d0,transparent:true,opacity:.8}));outline.frustumCulled=false;scene.add(outline)}if(!target){outline.visible=false;$('targetLabel').textContent='';return}outline.visible=true;outline.position.set(target.x+.5,target.y+.5,target.z+.5);$('targetLabel').textContent=BLOCK_BY_ID[target.id]?.name||'BLOCK'}
function startBreak(){if(!target)return;const b=BLOCK_BY_ID[target.id];if(!b?.hardness||target.id===22)return;breaking={...target,time:0,need:Math.max(.1,b.hardness*.42)}}
function breakTick(dt){if(!breaking)return;if(!locked||!target||target.x!==breaking.x||target.y!==breaking.y||target.z!==breaking.z||target.id!==breaking.id){breaking=null;showBreak(0);return}breaking.time+=dt;const p=Math.min(1,breaking.time/breaking.need);showBreak(p);if(p>=1){const b=BLOCK_BY_ID[breaking.id];changeBlock(breaking.x,breaking.y,breaking.z,0);give(b?.drop||Object.keys(BLOCKS).find(k=>BLOCKS[k].id===breaking.id),1);breaking=null;showBreak(0)}}
function showBreak(p){const bar=$('breakBar');if(p<=0){bar.classList.add('hidden');bar.querySelector('i').style.width='0%';return}bar.classList.remove('hidden');bar.querySelector('i').style.width=`${p*100}%`}
function place(){const slot=hot[hotIndex];if(!slot?.count||!BLOCK_BY_ID[slot.id]||!target)return;const n=target.normal,x=target.x+n.x,y=target.y+n.y,z=target.z+n.z;if(world.get(x,y,z)!==0)return;const test=new THREE.Vector3(x+.5,y,z+.5);if(collides(test))return;changeBlock(x,y,z,BLOCK_BY_ID[slot.id].id);slot.count--;buildHotbar()}
function give(id,count){if(!id)return;let s=hot.find(x=>x.id===id&&x.count<64);if(!s)s=hot.find(x=>!x.count);if(s){s.id=id;s.count=Math.min(64,s.count+count)}else inventory[id]=(inventory[id]||0)+count;buildHotbar()}
function toCss(n){return`#${Number(n).toString(16).padStart(6,'0').slice(-6)}`}
function buildHotbar(){const bar=$('hotbar');bar.innerHTML='';for(let i=0;i<9;i++){const s=hot[i]||{id:'',count:0},el=document.createElement('button');el.className=`hot ${i===hotIndex?'sel':''}`;el.type='button';const num=document.createElement('span');num.className='num';num.textContent=i+1;const icon=document.createElement('b');icon.className='item-icon';icon.textContent=s.id?'■':'';if(s.id)icon.style.backgroundColor=toCss(BLOCK_BY_ID[s.id]?.color||0xffffff);const count=document.createElement('small');count.textContent=s.count>1?s.count:'';el.append(num,icon,count);el.onclick=()=>{if(state==='PLAYING'){hotIndex=i;buildHotbar()}};bar.append(el)}}
function updateHud(){const hp=Math.max(0,Math.round(health)),hu=Math.max(0,Math.round(hunger));$('healthText').textContent=`${hp} / ${MAX}`;$('hungerText').textContent=`${hu} / ${MAX}`;drawIcons($('healthIcons'),hp,'health');drawIcons($('hungerIcons'),hu,'food');$('coords').style.display=settings.coords===false?'none':'block';if(player)$('coords').textContent=`X ${player.pos.x.toFixed(1)}  Y ${player.pos.y.toFixed(1)}  Z ${player.pos.z.toFixed(1)}`}
function drawIcons(parent,value,type){parent.innerHTML='';for(let i=0;i<MAX;i+=2){const amount=Math.max(0,Math.min(2,value-i)),icon=document.createElement('span');icon.className=`icon ${amount===2?'full':amount===1?'half':'empty'} ${type}`;parent.append(icon)}}
function damage(n){if(state!=='PLAYING'||n<=0)return;health=Math.max(0,health-n);updateHud();if(health<=0)die()}
function eat(){if(hunger>=MAX||inventory.apple<=0)return;inventory.apple--;hunger=Math.min(MAX,hunger+5);updateHud();save()}
function survivalTick(dt){hungerClock+=dt;regenClock+=dt;if(hungerClock>=30){hungerClock=0;hunger=Math.max(0,hunger-1);updateHud()}if(hunger<=0&&regenClock>=1){regenClock=0;damage(1)}if(hunger>=18&&health<MAX&&regenClock>=4){regenClock=0;health=Math.min(MAX,health+1);updateHud()}}
function openInventory(){if(state!=='PLAYING')return;setState('INVENTORY');screen('inventory');renderInventory()}
function closeInventory(){if(state!=='INVENTORY')return;screen(null);setState('PLAYING');requestLock()}
function renderInventory(){const grid=$('invGrid');grid.innerHTML='';for(const [id,count] of Object.entries(inventory)){if(!count)continue;const s=document.createElement('div');s.className='slot';s.innerHTML=`<b>${id==='apple'?'●':'■'}</b><em>${count}</em>`;if(BLOCK_BY_ID[id])s.querySelector('b').style.color=toCss(BLOCK_BY_ID[id].color||0xffffff);grid.append(s)}const hb=$('invHotbar');hb.innerHTML='';for(let i=0;i<9;i++){const s=hot[i]||{},el=document.createElement('div');el.className=`slot ${i===hotIndex?'selected':''}`;el.innerHTML=`<b>${s.id?'■':''}</b><em>${s.count||''}</em>`;if(s.id)el.querySelector('b').style.color=toCss(BLOCK_BY_ID[s.id]?.color||0xffffff);hb.append(el)}}
function pause(){if(state!=='PLAYING')return;save();screen('pause');setState('PAUSED')}
function resume(){if(state!=='PAUSED')return;screen(null);setState('PLAYING');requestLock()}
function die(){if(state==='DEAD')return;save();if(locked)document.exitPointerLock();screen('dead');setState('DEAD')}
function respawn(){if(!world)return;world.findSpawn();player.pos.set(world.spawn.x,world.spawn.y,world.spawn.z);health=20;hunger=20;velocity.set(0,0,0);screen(null);setState('PLAYING');updateHud();requestLock()}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(state==='PLAYING'){updatePlayer(dt);streamChunks();mpStateClock+=dt;if(mp?.peer&&mp.local&&mpStateClock>.08){mpStateClock=0;mp.sendState({position:{x:player.pos.x,y:player.pos.y,z:player.pos.z},rotation:{x:pitch,y:yaw},health,hunger,selectedSlot:hotIndex})}updateRemotePlayers(dt);target=raycast();updateOutline();breakTick(dt);survivalTick(dt);if(performance.now()-lastSave>10000){lastSave=performance.now();save()}}renderer.render(scene,camera)}
window.addEventListener('error',e=>console.error(e.error||e.message));window.addEventListener('unhandledrejection',e=>console.error(e.reason));init();