import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {World,seedNumber,CHUNK,HEIGHT} from './world.js';
import {BLOCKS,BLOCK_BY_ID,HOTBAR_BLOCKS} from './blocks.js';
const VERSION='0.1.0';let scene,camera,renderer,world,player,clock=new THREE.Clock(),locked=false,gameState='MENU',target=null,breaking=null,keys={},settings=JSON.parse(localStorage.getItem('voxelSettings')||'{}');
const $=id=>document.getElementById(id),show=id=>{$('menu').classList.add('hidden');$('worlds').classList.add('hidden');$('create').classList.add('hidden');$('pause').classList.add('hidden');$('settings').classList.add('hidden');$('about').classList.add('hidden');$('inventory').classList.add('hidden');$('dead').classList.add('hidden');if(id)$(`${id}`).classList.remove('hidden')};
const inv=Object.fromEntries([...Object.keys(BLOCKS), 'coal','raw_iron','raw_copper','raw_gold','diamond'].map(x=>[x,0]));let hot=HOTBAR_BLOCKS.map(x=>({id:x,count:x==='dirt'?16:0}));let health=20,hunger=20,yaw=0,pitch=0,vel=new THREE.Vector3(),onGround=false,lastSave=0;
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x8fc7e7);scene.fog=new THREE.Fog(0x8fc7e7,40,100);camera=new THREE.PerspectiveCamera(settings.fov||75,innerWidth/innerHeight,.05,180);renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=false;$('game').appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xd9efff,0x5b503f,1.8));const sun=new THREE.DirectionalLight(0xffffff,1.1);sun.position.set(40,80,20);scene.add(sun);buildHotbar();events();requestAnimationFrame(loop)}
function events(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code.startsWith('Digit')){const n=+e.code.slice(5);if(n>=1&&n<=9){hotIndex=n-1;buildHotbar()}}if(e.code==='KeyE'&&gameState==='PLAYING')openInventory();if(e.code==='Escape'&&gameState==='PLAYING')pause();if(e.code==='Escape'&&gameState==='PAUSED')resume()});document.addEventListener('keyup',e=>keys[e.code]=false);renderer.domElement.addEventListener('click',()=>{if(gameState==='PLAYING')renderer.domElement.requestPointerLock()});document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===renderer.domElement);document.addEventListener('mousemove',e=>{if(!locked)return;const s=(settings.sens||8)*.0009;yaw-=e.movementX*s;pitch-=e.movementY*s;pitch=Math.max(-1.54,Math.min(1.54,pitch))});renderer.domElement.addEventListener('mousedown',e=>{if(!locked||!target)return;e.preventDefault();if(e.button===0)startBreak();if(e.button===2)place()});renderer.domElement.addEventListener('wheel',e=>{if(!locked)return;hotIndex=(hotIndex+(e.deltaY>0?1:-1)+9)%9;buildHotbar()});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());$('playBtn').onclick=()=>{$('worldsBtn').click()};$('worldsBtn').onclick=()=>{refreshWorlds();show('worlds');gameState='WORLDS'};$('createBtn').onclick=()=>{show('create');gameState='CREATE'};$('startWorld').onclick=startNew;$('resumeBtn').onclick=resume;$('quitBtn').onclick=()=>{save();locked&&document.exitPointerLock();show('menu');$('hud').classList.add('hidden');gameState='MENU'};$('settingsBtn').onclick=()=>{show('settings');gameState='SETTINGS'};$('pauseSettings').onclick=()=>{show('settings');gameState='SETTINGS'};$('aboutBtn').onclick=()=>{show('about');gameState='ABOUT'};document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>{show(b.dataset.back);gameState=b.dataset.back.toUpperCase()});$('closeInv').onclick=()=>closeInventory();$('respawnBtn').onclick=()=>respawn();$('deadMenu').onclick=()=>{show('menu');$('hud').classList.add('hidden');gameState='MENU'};$('fov').oninput=e=>{camera.fov=+e.target.value;camera.updateProjectionMatrix();saveSettings()};$('sens').oninput=saveSettings;$('volume').oninput=saveSettings;$('rd').oninput=saveSettings;$('coordsToggle').onchange=saveSettings;$('bobToggle').onchange=saveSettings}
let hotIndex=0;
function startNew(){const name=$('worldName').value.trim()||'New World',seed=seedNumber($('worldSeed').value.trim()),type=$('worldType').value;world=new World(seed,type);world.findSpawn();player={pos:new THREE.Vector3(world.spawn.x,world.spawn.y,world.spawn.z),height:1.8,width:.6};health=20;hunger=20;for(const k in inv)inv[k]=0;inv.dirt=16;hot=HOTBAR_BLOCKS.map(x=>({id:x,count:x==='dirt'?16:0}));localStorage.setItem('voxelWorld:'+name,JSON.stringify({name,seed,type,player:{x:player.pos.x,y:player.pos.y,z:player.pos.z},health,hunger,inv,hot,time:0}));enterWorld();}
function enterWorld(){show(null);$('loading').classList.remove('hidden');gameState='LOADING';world.clearMeshes();let done=0,total=25;const d=+$('renderDistance').value||3;function step(){if(done<total){done++;const a=Math.floor(Math.sqrt(done/total)*(d+1));world.loadNear(player.pos.x,player.pos.z,Math.max(1,a),scene);$('loadBar').style.width=(done/total*100)+'%';$('loadText').textContent=`Generating world... ${done}/${total}`;setTimeout(step,15)}else{$('loading').classList.add('hidden');$('hud').classList.remove('hidden');gameState='PLAYING';renderer.domElement.requestPointerLock();}}step()}
function refreshWorlds(){const box=$('worldList');box.innerHTML='';for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k?.startsWith('voxelWorld:'))continue;try{const w=JSON.parse(localStorage.getItem(k));const row=document.createElement('div');row.className='worldRow';row.innerHTML=`<strong>${esc(w.name)}</strong><small>Seed: ${w.seed}</small><button>Play</button><button class="delete">Delete</button>`;row.children[1].onclick=()=>loadWorld(k);row.children[2].onclick=()=>{if(confirm(`Delete "${w.name}"?`)){localStorage.removeItem(k);refreshWorlds()}};box.appendChild(row)}catch{localStorage.removeItem(k)}}}
function loadWorld(k){const w=JSON.parse(localStorage.getItem(k));world=new World(w.seed,w.type);world.modified=new Map(Object.entries(w.modified||{}).map(([k,v])=>[k,+v]));player={pos:new THREE.Vector3(w.player.x,w.player.y,w.player.z),height:1.8,width:.6};health=w.health??20;hunger=w.hunger??20;Object.assign(inv,w.inv||{});hot=w.hot||hot;enterWorld()}
function save(){if(!world||!player)return;let name='Autosave';for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('voxelWorld:')){try{const w=JSON.parse(localStorage.getItem(k));if(Math.abs(w.player?.x-player.pos.x)<1e9)name=w.name}catch{}}}localStorage.setItem('voxelWorld:'+name,JSON.stringify({saveVersion:1,name,seed:world.seed,type:world.type,player:{x:player.pos.x,y:player.pos.y,z:player.pos.z},health,hunger,inv,hot,modified:Object.fromEntries(world.modified),time:world.time||0}))}
function saveSettings(){settings={fov:+$('fov').value,sens:+$('sens').value,volume:+$('volume').value,rd:+$('rd').value,coords:$('coordsToggle').checked,bob:$('bobToggle').checked};localStorage.setItem('voxelSettings',JSON.stringify(settings))}
function solidAt(x,y,z){const id=world.get(x,y,z);return BLOCK_BY_ID[id]?.solid&&!BLOCK_BY_ID[id]?.transparent}
function collide(pos){const minX=Math.floor(pos.x-.3),maxX=Math.floor(pos.x+.3),minY=Math.floor(pos.y),maxY=Math.floor(pos.y+1.8),minZ=Math.floor(pos.z-.3),maxZ=Math.floor(pos.z+.3);for(let x=minX;x<=maxX;x++)for(let y=minY;y<=maxY;y++)for(let z=minZ;z<=maxZ;z++)if(solidAt(x,y,z))return true;return false}
function updatePlayer(dt){let dir=new THREE.Vector3();if(keys.KeyW)dir.z-=1;if(keys.KeyS)dir.z+=1;if(keys.KeyA)dir.x-=1;if(keys.KeyD)dir.x+=1;if(dir.lengthSq())dir.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw);const speed=keys.ShiftLeft||keys.ShiftRight?7:4.5;vel.x=dir.x*speed;vel.z=dir.z*speed;if((keys.Space)&&onGround){vel.y=8;onGround=false}vel.y-=22*dt;const next=player.pos.clone();next.x+=vel.x*dt;if(!collide(next))player.pos.x=next.x;next.copy(player.pos);next.z+=vel.z*dt;if(!collide(next))player.pos.z=next.z;next.copy(player.pos);next.y+=vel.y*dt;if(!collide(next)){player.pos.y=next.y;onGround=false}else{if(vel.y<0){onGround=true}vel.y=0}if(player.pos.y<-10){health=0;die()}camera.position.set(player.pos.x,player.pos.y+1.62,player.pos.z);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;if(settings.coords!==false)$('coords').textContent=`XYZ: ${player.pos.x.toFixed(1)} ${player.pos.y.toFixed(1)} ${player.pos.z.toFixed(1)}`;else $('coords').textContent='';}
const ray=new THREE.Raycaster();function findTarget(){if(!world||gameState!=='PLAYING')return null;ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=raycastVoxel(ray,6);return hits}
function raycastVoxel(r,max){const step=.08,p=r.origin.clone();for(let d=0;d<=max;d+=step){const x=Math.floor(p.x),y=Math.floor(p.y),z=Math.floor(p.z),id=world.get(x,y,z);if(id&&BLOCK_BY_ID[id]?.solid)return{x,y,z,id,normal:r.direction.clone().multiplyScalar(-1).normalize(),distance:d};p.addScaledVector(r.direction,step)}return null}
function startBreak(){if(!target)return;const b=BLOCK_BY_ID[target.id];const tool=hot[hotIndex]?.id;const mult=tool?.includes('pickaxe')?2:1;breaking={x:target.x,y:target.y,z:target.z,t:0,need:Math.max(.08,b.hardness/(mult*2))}}
function updateBreak(dt){if(!breaking||!target||breaking.x!==target.x||breaking.y!==target.y||breaking.z!==target.z){breaking=null;return}if(!locked)return;breaking.t+=dt;if(breaking.t>=breaking.need){const id=breaking.id||target.id;const drop=BLOCKS[id]?.drop||Object.keys(BLOCKS).find(k=>BLOCKS[k].id===id);world.set(target.x,target.y,target.z,0);give(drop||'dirt',1);breaking=null}}
function place(){const b=hot[hotIndex];if(!b||b.count<=0)return;const t=target;if(!t)return;const n=t.normal;const x=t.x+Math.round(n.x),y=t.y+Math.round(n.y),z=t.z+Math.round(n.z);if(world.get(x,y,z)!==0)return;const test=player.pos.clone();if(Math.abs(x+.5-player.pos.x)<.8&&Math.abs(z+.5-player.pos.z)<.8&&y<player.pos.y+2&&y+1>player.pos.y)return;world.set(x,y,z,BLOCKS[b.id].id);b.count--;buildHotbar()}
function give(id,n){if(!id)return;const slot=hot.find(s=>s.id===id&&s.count<64);if(slot)slot.count=Math.min(64,slot.count+n);else{const empty=hot.find(s=>!s.count);if(empty){empty.id=id;empty.count=n}else inv[id]=(inv[id]||0)+n}buildHotbar()}
function buildHotbar(){const box=$('hotbar');box.innerHTML='';hot.forEach((s,i)=>{const d=document.createElement('div');d.className='hot '+(i===hotIndex?'sel':'');const b=BLOCKS[s.id];d.innerHTML=`<b style="color:#${(b?.color||0xffffff).toString(16).padStart(6,'0')}">■</b><small>${s.count||''}</small>`;d.onclick=()=>{hotIndex=i;buildHotbar()};box.appendChild(d)})}
function openInventory(){gameState='INVENTORY';document.exitPointerLock();renderInventory();$('inventory').classList.remove('hidden')};function closeInventory(){$('inventory').classList.add('hidden');gameState='PLAYING'}
function renderInventory(){const g=$('invGrid');g.innerHTML='';Object.entries(inv).forEach(([id,c])=>{if(!c)return;const d=document.createElement('div');d.className='slot';d.innerHTML=`<b>${id.slice(0,2).toUpperCase()}</b><em>${c}</em>`;d.title=id;d.onclick=()=>{if(c>0){give(id,1);inv[id]--;renderInventory()}};g.appendChild(d)});const h=$('invHotbar');h.innerHTML='';hot.forEach((s,i)=>{const d=document.createElement('div');d.className='slot '+(i===hotIndex?'selected':'');d.textContent=s.id.slice(0,2).toUpperCase()+' '+(s.count||0);h.appendChild(d)})}
function pause(){gameState='PAUSED';document.exitPointerLock();show('pause')};function resume(){show(null);gameState='PLAYING';renderer.domElement.requestPointerLock()};function die(){if(gameState==='DEAD')return;health=0;document.exitPointerLock();gameState='DEAD';show('dead');$('hud').classList.add('hidden')};function respawn(){health=20;hunger=20;player.pos.set(world.spawn.x,world.spawn.y,world.spawn.z);$('dead').classList.add('hidden');$('hud').classList.remove('hidden');gameState='PLAYING';renderer.domElement.requestPointerLock()};
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);if(gameState==='PLAYING'){updatePlayer(dt);world.loadNear(player.pos.x,player.pos.z,Math.max(1,+$('rd').value||3),scene);target=findTarget();updateBreak(dt);if(++lastSave>600){save();lastSave=0}}renderer.render(scene,camera)}function esc(s){return s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#39;'}[c]))}
init();show('menu');gameState='MENU';