import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {BLOCKS,BLOCK_BY_ID} from './blocks.js';
export const CHUNK=16, HEIGHT=64;
function hash(x,z,s){let n=Math.imul(x,374761393)^Math.imul(z,668265263)^s;n=Math.imul(n^(n>>>13),1274126177);return (n^(n>>>16))>>>0}
export function seedNumber(v){if(v==='')return Math.floor(Math.random()*2147483647);if(/^-?\d+$/.test(v))return Number(v)|0;let n=2166136261;for(const c of v)n=Math.imul(n^c.charCodeAt(0),16777619);return n|0}
function noise(x,z,s){const xi=Math.floor(x),zi=Math.floor(z),xf=x-xi,zf=z-zi;const f=t=>t*t*(3-2*t),r=(a,b)=>{const h=hash(a,b,s)/4294967295;return h*2-1};const a=r(xi,zi),b=r(xi+1,zi),c=r(xi,zi+1),d=r(xi+1,zi+1);return a+(b-a)*f(xf)+(c-a)*f(zf)+(d-b-c+a)*f(xf)*f(zf)}
export class World{constructor(seed,type='Normal'){this.seed=seed;this.type=type;this.chunks=new Map();this.modified=new Map();this.meshes=new Map();this.spawn={x:.5,y:40,z:.5}}
key(cx,cz){return `${cx},${cz}`} height(x,z){if(this.type==='Flat')return 30;let n=noise(x*.018,z*.018,this.seed)*10+noise(x*.045,z*.045,this.seed+9)*4;return Math.max(5,Math.floor(30+n+(noise(x*.006,z*.006,this.seed+77)+1)*9))}
biome(x,z){let n=noise(x*.008,z*.008,this.seed+100);return n<-.32?'desert':n>.38?'forest':(noise(x*.015,z*.015,this.seed+101)>.55?'mountain':'plains')}
baseBlock(x,y,z){if(y<0)return 22;const h=this.height(x,z),b=this.biome(x,z);if(y>h)return y<=1?21:0;if(y===h){if(b==='desert')return 5;if(b==='mountain'&&h>47)return 14;return 1}if(y>h-4)return b==='desert'?5:2;if(y<7)return 3;const q=hash(x,y,z^this.seed);if(y<24&&(q%180)===0)return 13;if(y<32&&(q%75)===0)return 12;if(y<40&&(q%40)===0)return 11;if(y<45&&(q%24)===0)return 10;if((q%19)===0)return 9;return 3}
get(x,y,z){if(y<0||y>=HEIGHT)return y<0?22:0;const k=`${x},${y},${z}`;if(this.modified.has(k))return this.modified.get(k);return this.baseBlock(x,y,z)}
set(x,y,z,id){if(y<0||y>=HEIGHT)return;const k=`${x},${y},${z}`,base=this.baseBlock(x,y,z);if(id===base)this.modified.delete(k);else this.modified.set(k,id);this.rebuildAround(x,z)}
ensure(cx,cz){const k=this.key(cx,cz);if(this.chunks.has(k))return;this.chunks.set(k,true)}
rebuildAround(x,z){const cx=Math.floor(x/CHUNK),cz=Math.floor(z/CHUNK);for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)this.rebuild(cx+dx,cz+dz)}
rebuild(cx,cz){this.ensure(cx,cz);if(this.meshes.has(this.key(cx,cz))){this.meshes.get(this.key(cx,cz)).removeFromParent();this.meshes.delete(this.key(cx,cz))}}
meshChunk(cx,cz,scene){const key=this.key(cx,cz);if(this.meshes.has(key))return;const pos=[],col=[],indices=[];const colors=new THREE.Color();const add=(x,y,z,face,id)=>{const b=BLOCK_BY_ID[id];if(!b||id===0)return;const c=new THREE.Color(b.color||0xffffff);const base=pos.length/3;const faces=[[[0,0,0],[1,0,0],[1,1,0],[0,1,0]],[[1,0,0],[1,0,1],[1,1,1],[1,1,0]],[[1,0,1],[0,0,1],[0,1,1],[1,1,1]],[[0,0,1],[0,0,0],[0,1,0],[0,1,1]],[[0,1,0],[1,1,0],[1,1,1],[0,1,1]],[[0,0,1],[1,0,1],[1,0,0],[0,0,0]]];const shade=[.82,.9,.78,.72,1,.62][face];for(const v of faces[face]){pos.push(x+v[0],y+v[1],z+v[2]);col.push(c.r*shade,c.g*shade,c.b*shade)}indices.push(base,base+1,base+2,base,base+2,base+3)};
const sx=cx*CHUNK,sz=cz*CHUNK;for(let x=sx;x<sx+CHUNK;x++)for(let z=sz;z<sz+CHUNK;z++)for(let y=0;y<HEIGHT;y++){const id=this.get(x,y,z);if(!id)continue;for(let f=0;f<6;f++){const nx=x+(f===1?1:f===3?-1:0),ny=y+(f===4?1:f===5?-1:0),nz=z+(f===2?1:f===0?-1:0);const nid=this.get(nx,ny,nz);if(!nid||!BLOCK_BY_ID[nid]?.solid||BLOCK_BY_ID[nid]?.transparent)add(x,y,z,f,id)}}if(!pos.length)return;const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(col,3));geo.setIndex(indices);geo.computeVertexNormals();const mat=new THREE.MeshLambertMaterial({vertexColors:true,transparent:true,opacity:.94});const m=new THREE.Mesh(geo,mat);scene.add(m);this.meshes.set(key,m)}
loadNear(px,pz,dist,scene){const pcx=Math.floor(px/CHUNK),pcz=Math.floor(pz/CHUNK);for(let dx=-dist;dx<=dist;dx++)for(let dz=-dist;dz<=dist;dz++){if(dx*dx+dz*dz>dist*dist)continue;this.ensure(pcx+dx,pcz+dz);this.meshChunk(pcx+dx,pcz+dz,scene)}}
clearMeshes(){for(const m of this.meshes.values())m.removeFromParent();this.meshes.clear()}
findSpawn(){for(let r=0;r<80;r++)for(let x=-r;x<=r;x++)for(const z of [-r,r]){const y=this.height(x,z);if(this.get(x,y+1,z)===0){this.spawn={x:x+.5,y:y+1.01,z:z+.5};return}}this.spawn={x:.5,y:this.height(0,0)+1.01,z:.5}}
}